name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer PHP et extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pdo_mysql, mbstring

    - name: Installer Composer
      run: composer install --no-progress --no-suggest

    - name: Lancer les tests
      run: phpunit tests/

    - name: Vérifier la syntaxe PHP
      run: php -l src/
