name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Configurer PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pdo_mysql, mbstring

    - name: Installer les dépendances via Composer
      run: composer install --no-progress --no-suggest

    - name: Lancer les tests PHPUnit
      run: vendor/bin/phpunit --configuration phpunit.xml
